Revert "Python Classroom: Share disk size declaration between disk and live"
This reverts commit 093733933f3035b45f723953fc91b1c285437bec.

    BuildError: Failed to parse kickstart file '.../fedora-disk-python-classroom.ks' : The following problem occurred on line 12 of the kickstart file:

    The part/partition and autopart commands can't be used at the same time.