Revert "Python Classroom: Share disk size declaration between disk and live"
This reverts commit 3459312f7baa735578b2d25890aab1742ade5bef.

    BuildError: Failed to parse kickstart file '.../fedora-disk-python-classroom.ks' : The following problem occurred on line 12 of the kickstart file:

    The part/partition and autopart commands can't be used at the same time.